### ISSUE TITLE
Available property types missing in docs

### ISSUE THREAD

**Issue by cb-tomsearle** [pdevito3/wrapt.dev#9]
On the page https://wrapt.dev/docs/entities#properties I can see some examples of properties, and that they can be nullable, but no information about which properties are available. Other than that, the tool looks great!

**Comment by pdevito3** [comment]
You're talking about the available data types, nullable and otherwise, that can be assigned to a property (e.g. `int?`, `DateTime`, `Guid`, etc)?

If so, this is just a free string that will be added next to the property, so all standard c# data types can be used. You even do custom properties like classes that act as foreign keys for instance. 

Hope this helps. If I'm missing the mark let me know and we'll figure it out.

**Comment by cb-tomsearle** [comment]
Ah OK that makes sense. I was just looking to assign a `datetime` which I found in the example entity but I wouldn't have known that all c# data types are available. Maybe that line you put in the response above would be good in the table under entity properties > properties > Type?

> All standard c# data types can be used. You even do custom properties like classes that act as foreign keys for instance.

Love the project by the way, great work!
